### PR TITLE
Expanded on 'defer execution'

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
Changed "_Defer execution_" to "_Defer the execution of code_"

### CODE REVIEW

**Comment by WyriHaximus** [comment]
`code` feels to generic, `callables` is more specific to what the event loop would be doing.

**Comment by AndrewCarterUK** [comment]
What about using `callbacks`? In [the PHP docs](http://php.net/manual/en/language.types.callable.php) `callable` is the typehint and it is referred to as a `callback`. It's probably a more universally understood term too?

**Comment by WyriHaximus** [comment]
`callbacks` implies:

``` php
function ()
{
    // Do something
}
```

While `callable` can also be:

``` php
[$class, 'method']
```

It provides more flexibility and especially in PHP 7 any callable can be called with `$callable()`

**Comment by AndrewCarterUK** [comment]
Persuaded.

**Comment by WyriHaximus** [comment]
:+1:

**Pull request merged**
